dbt_ods:
  outputs:
    dev:
      type: singlestore
      host: dev-tlv-memagg01.gw-4u.com
      port: 3306
      user: dev_user
      password:
      database: ods
      schema: ods
      threads: 1
  target: dev