version: '3.7'

networks:
  my_network:
    driver: bridge

services:
    postgres:
        image: postgres:10-alpine
        networks:
            - my_network
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    dbt:
        image: dbt_ods
        networks:
            - my_network
        volumes:
            - /Users/arielsoothy/PycharmProjects/dbt_ods

    local-runner:
        image: amazon/mwaa-local:2_4
        networks:
            - my_network
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/dags:/usr/local/airflow/dags"
            - "${PWD}/plugins:/usr/local/airflow/plugins"
            - "${PWD}/requirements:/usr/local/airflow/requirements"
            - "${PWD}/config:/usr/local/airflow/config"
            - "${PWD}/startup_script:/usr/local/airflow/startup"
            - "${PWD}/docker/variables.json:/usr/local/airflow/variables.json"
            - "${PWD}/docker/script/connections.sh:/usr/local/airflow/connections.sh"
            - "~/.aws:/usr/local/airflow/.aws"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/Users/arielsoothy/PycharmProjects/dbt_ods:/dbt/project"
        ports:
            - "8080:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
            - ./config/.env.localrunner